AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'active_storage_dashboard.gemspec' 